import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

// DESIGN-0003: the shared `docs/` tree lives at the repo root, not under
// `site/src/content/docs/`. We expose it to Starlight via a symlink at
// `site/src/content/docs -> ../../../docs` so the bundled `docsLoader()`
// — which hardcodes the `src/content/docs/` location and whose path
// math drives sidebar autogenerate — works without modification. A
// bare `glob({ base: '../docs' })` loader does serve content pages,
// but Starlight's autogenerate filter strips `src/content/docs/` from
// each entry's filePath and matches the remainder against the
// `directory` argument; with our entries at `../docs/...`, the strip
// never fires and every autogenerated group renders empty.
// See `node_modules/@astrojs/starlight/utils/collection.ts:25-37` for
// the prefix-strip implementation.
//
// Frontmatter compatibility: docz emits `id`, `status`, `author`, and
// `created`. Starlight's docsSchema doesn't know those fields, so we
// extend it with them as optional. `title` and the rest of Starlight's
// surface stay untouched.
export const collections = {
	docs: defineCollection({
		loader: docsLoader(),
		schema: docsSchema({
			extend: z.object({
				id: z.string().optional(),
				status: z.string().optional(),
				author: z.string().optional(),
				created: z.union([z.string(), z.date()]).optional(),
			}),
		}),
	}),
};
