package upstream

import (
	"errors"
	"fmt"
	"maps"
	"slices"
	"strings"
	"unicode/utf8"
)

// The digest is a machine artifact. This is the same facts written for
// a person.
//
// A user who hits "unknown tool: Frobnicate" wants to know what the
// documented list is and where it came from. A contributor adding a
// rule wants to know which documented fields nothing reads yet. Both
// questions are answered by the digest plus the coverage table plus the
// acknowledgement reasons, and neither is answerable by reading JSON.
//
// The page is generated, never edited: `render --check` fails when the
// committed file differs from a fresh render, so it cannot drift from
// the digest it describes.

// SpecPagePath is the committed rendered page.
const SpecPagePath = "docs/rules/upstream-spec.md"

// ErrStale is the sentinel behind exit 1 for `render --check`: the
// committed page no longer matches the digest.
var ErrStale = errors.New("the committed spec page is out of date")

// Coverage column values. They are three states rather than two: "no
// opinion" is not the same claim as "documented and not read".
const (
	coverYes     = "yes"
	coverNo      = "no"
	coverUnknown = "—"
)

// RenderSpec renders the human-facing spec page.
//
// It is named RenderSpec rather than Render because the package already
// has an unexported render() for report formats, and two functions
// named for the same verb in one package is one too many.
func RenderSpec(d *Digest, ack Acknowledged, cov Coverage) ([]byte, error) {
	if err := cov.Validate(d); err != nil {
		return nil, err
	}

	r := &renderer{digest: d, ack: ack, cov: cov}
	r.writeAll()

	return []byte(r.b.String()), nil
}

// renderer carries the three inputs so the per-section methods read as
// prose rather than as parameter lists.
type renderer struct {
	b      strings.Builder
	digest *Digest
	ack    Acknowledged
	cov    Coverage
}

// writeAll emits the page in a fixed order. The order is the reading
// order of the rules doc, not the alphabetical order of the digest.
func (r *renderer) writeAll() {
	r.writeHeader()
	r.writeTools()
	r.writeHooks()
	r.writeSkills()
	r.writeAgents()
	r.writePlugins()
	r.writeMarketplace()
	r.writeMCP()
	r.writePortable()
	r.writeDisagreements()
}

func (r *renderer) writeHeader() {
	r.b.WriteString("---\ntitle: Upstream spec\n---\n\n")
	r.b.WriteString("<!-- Generated by `go run ./cmd/specdrift render`. Do not edit. -->\n\n")
	r.b.WriteString("# Upstream spec\n\n")
	r.b.WriteString("What the published Claude Code and Agent Skills documentation describes, " +
		"and how much of it claudelint reads.\n\n")
	fmt.Fprintf(&r.b, "Verified against Claude Code v%s; documentation pages carried markers up to %s.\n\n",
		r.digest.Meta.ClaudeCodeLatest, r.digest.Meta.DocsMaxMarker)
	r.b.WriteString("The **claudelint** column answers one question: does anything in the linter " +
		"read this? A `no` is not a bug on its own — it means no rule needs the field yet, and " +
		"the reason says which rule or phase would change that. A `—` means claudelint has no " +
		"opinion about the section at all.\n\n")
	r.b.WriteString("This page is generated from `internal/upstream/digest.json` and " +
		"`internal/upstream/acknowledged.json`. A weekly job re-extracts the digest from " +
		"upstream, so a row here is what the documentation said the last time anyone looked.\n")
}

func (r *renderer) writeTools() {
	r.section("Tools", "The built-in tools a skill, command, or agent may name in "+
		"`allowed-tools`, `disallowed-tools`, or `tools`.")

	r.nameTable("tools.builtin", "Tool", r.digest.Tools.Builtin)

	if len(r.digest.Tools.Deprecated) > 0 {
		fmt.Fprintf(&r.b, "\nStill documented but marked deprecated: %s.\n",
			codeList(r.digest.Tools.Deprecated))
	}
	r.b.WriteString("\nTools that upstream renamed or removed are no longer in the table above. " +
		"claudelint still recognizes them, and reports them with their replacement rather than " +
		"as typos — see [Deprecated and removed tools](rules.md#deprecated-and-removed-tools).\n")
}

func (r *renderer) writeHooks() {
	r.section("Hooks", "Hook events, handler types, and the fields a handler entry may carry.")

	r.subsection("Events")
	r.nameTable("hooks.events", "Event", r.digest.Hooks.Events)

	r.subsection("Handler types")
	r.nameTable("hooks.types", "Type", r.digest.Hooks.Types)

	r.subsection("Handler fields")
	r.b.WriteString("Grouped as the documentation groups them: `common` fields apply to every " +
		"handler, the rest to one type.\n\n")
	for _, group := range slices.Sorted(maps.Keys(r.digest.Hooks.HandlerFields)) {
		fmt.Fprintf(&r.b, "`%s`:\n\n", group)
		r.fieldTable("hooks.handler_fields", r.digest.Hooks.HandlerFields[group])
		r.b.WriteString("\n")
	}

	r.subsection("Timeout defaults")
	r.b.WriteString("Seconds applied when a handler declares no `timeout`.\n\n")
	r.intTable("By type", r.digest.Hooks.TimeoutDefaults.ByType)
	r.intTable("By event", r.digest.Hooks.TimeoutDefaults.ByEvent)
}

func (r *renderer) writeSkills() {
	r.section("Skills and commands",
		"Skills and commands share one documented frontmatter table. claudelint splits it "+
			"across two parsers, so a field is marked read when either reads it.")

	r.fieldTable("skills.frontmatter", r.digest.Skills.Frontmatter)

	if len(r.digest.Skills.Substitutions) > 0 {
		fmt.Fprintf(&r.b, "\nDocumented string substitutions: %s.\n",
			codeList(r.digest.Skills.Substitutions))
	}
	if len(r.digest.Skills.PortableFields) > 0 {
		fmt.Fprintf(&r.b, "\nUsable outside Claude Code: %s.\n",
			codeList(r.digest.Skills.PortableFields))
	}
}

func (r *renderer) writeAgents() {
	r.section("Agents", "Subagent frontmatter and the values its enum fields accept.")

	r.fieldTable("agents.frontmatter", r.digest.Agents.Frontmatter)

	r.subsection("Enums")
	for _, field := range slices.Sorted(maps.Keys(r.digest.Agents.Enums)) {
		fmt.Fprintf(&r.b, "`%s`:\n\n", field)
		r.nameTable("agents.enums."+field, "Value", r.digest.Agents.Enums[field])
		r.b.WriteString("\n")
	}
}

func (r *renderer) writePlugins() {
	r.section("Plugins", "The plugin manifest and where a plugin's components live.")

	r.fieldTable("plugins.manifest_fields", r.digest.Plugins.ManifestFields)

	r.subsection("Component locations")
	r.stringTable("Component", "Path", r.digest.Plugins.Locations)
}

func (r *renderer) writeMarketplace() {
	r.section("Marketplaces", "The marketplace manifest, its plugin entries, and the source "+
		"shapes a plugin entry may declare.")

	r.fieldTable("marketplace.fields", r.digest.Marketplace.Fields)

	r.subsection("Owner")
	r.fieldTable("marketplace.owner_fields", r.digest.Marketplace.OwnerFields)

	r.subsection("Plugin entries")
	r.fieldTable("marketplace.plugin_entry_fields", r.digest.Marketplace.PluginEntryFields)

	r.subsection("Source kinds")
	t := newTable("Kind", "Required", "Optional", "claudelint")
	for _, kind := range slices.Sorted(maps.Keys(r.digest.Marketplace.Sources)) {
		shape := r.digest.Marketplace.Sources[kind]
		t.add("`"+kind+"`", codeList(shape.Required), codeList(shape.Optional),
			r.coverage("marketplace.sources", kind))
	}
	t.write(&r.b)

	r.subsection("Reserved names")
	r.b.WriteString("Reserved for official Anthropic use. A manifest shipping one stops " +
		"loading for every user.\n\n")
	r.nameTable("marketplace.reserved_names", "Name", r.digest.Marketplace.ReservedNames)
}

func (r *renderer) writeMCP() {
	r.section("MCP servers", "The shape of one entry in `.mcp.json` or a plugin's `mcp.servers`.")

	r.fieldTable("mcp.server_fields", r.digest.MCP.ServerFields)

	r.subsection("Transports")
	r.nameTable("mcp.transports", "Transport", r.digest.MCP.Transports)
}

func (r *renderer) writePortable() {
	r.section("Portable skills", "The Agent Skills specification, which is narrower than the "+
		"Claude Code superset above. claudelint does not enforce it yet; it is recorded so a "+
		"future portability rule has something to read.")

	fmt.Fprintf(&r.b, "Name pattern: `%s`\n\n", r.digest.Portable.NamePattern)
	fmt.Fprintf(&r.b, "Allowed fields: %s\n", codeList(r.digest.Portable.AllowedFields))
	if len(r.digest.Portable.AnthropicAllowedFields) > 0 {
		fmt.Fprintf(&r.b, "\nAllowed by Anthropic's own validator: %s\n",
			codeList(r.digest.Portable.AnthropicAllowedFields))
	}
	if len(r.digest.Portable.Limits) > 0 {
		r.b.WriteString("\n")
		r.intTable("Limits", r.digest.Portable.Limits)
	}
}

func (r *renderer) writeDisagreements() {
	r.section("Documentation versus SchemaStore",
		"Where the published documentation and the SchemaStore JSON schemas describe different "+
			"things. The documentation wins: these are recorded, not enforced.")

	if len(r.digest.Disagreements) == 0 {
		r.b.WriteString("None on the last extraction.\n")

		return
	}

	t := newTable("Topic", "Source", "Documented only", "Source only")
	for i := range r.digest.Disagreements {
		d := &r.digest.Disagreements[i]
		t.add("`"+d.Topic+"`", "`"+d.Source+"`", codeList(d.DocsOnly), codeList(d.SourceOnly))
	}
	t.write(&r.b)
}

// section writes a level-2 heading and its lead paragraph.
func (r *renderer) section(title, intro string) {
	fmt.Fprintf(&r.b, "\n## %s\n\n%s\n\n", title, intro)
}

// subsection writes a level-3 heading.
func (r *renderer) subsection(title string) {
	fmt.Fprintf(&r.b, "\n### %s\n\n", title)
}

// fieldTable renders a documented field table with the coverage and
// reason columns appended.
func (r *renderer) fieldTable(path string, fields []Field) {
	t := newTable("Field", "Required", "Type", "claudelint", "Reason")
	for i := range fields {
		f := &fields[i]
		t.add("`"+f.Name+"`", orDash(f.Required), typeCell(f.Type),
			r.coverage(path, f.Name), orDash(r.reason(path, f.Name)))
	}
	t.write(&r.b)
}

// nameTable renders a plain documented name set.
func (r *renderer) nameTable(path, header string, names []string) {
	t := newTable(header, "claudelint", "Reason")
	for _, name := range names {
		t.add("`"+name+"`", r.coverage(path, name), orDash(r.reason(path, name)))
	}
	t.write(&r.b)
}

// intTable renders a documented name-to-number map.
func (r *renderer) intTable(header string, values map[string]int) {
	if len(values) == 0 {
		return
	}

	t := newTable(header, "Seconds")
	for _, key := range slices.Sorted(maps.Keys(values)) {
		t.add("`"+key+"`", fmt.Sprint(values[key]))
	}
	t.write(&r.b)
	r.b.WriteString("\n")
}

// stringTable renders a documented name-to-string map.
func (r *renderer) stringTable(keyHeader, valueHeader string, values map[string]string) {
	t := newTable(keyHeader, valueHeader)
	for _, key := range slices.Sorted(maps.Keys(values)) {
		t.add(key, "`"+values[key]+"`")
	}
	t.write(&r.b)
}

// coverage renders the three-state answer for one item.
func (r *renderer) coverage(path, item string) string {
	known, parsed := r.cov.Lookup(path, item)
	switch {
	case !known:
		return coverUnknown
	case parsed:
		return coverYes
	default:
		return coverNo
	}
}

// reason returns the acknowledgement reason for an item, if one exists.
func (r *renderer) reason(path, item string) string {
	reason, _ := r.ack.Reason(path, item)

	return reason
}

// table accumulates rows and writes them with aligned pipes. Alignment
// is a requirement, not a nicety: this repo's Markdown lint rejects
// unaligned tables (MD060).
type table struct {
	head []string
	rows [][]string
}

func newTable(head ...string) *table { return &table{head: head} }

func (t *table) add(cells ...string) { t.rows = append(t.rows, cells) }

// write emits the table, padding every column to its widest cell.
func (t *table) write(b *strings.Builder) {
	widths := make([]int, len(t.head))
	for i, h := range t.head {
		widths[i] = cellWidth(h)
	}
	for _, row := range t.rows {
		for i, cell := range row {
			if n := cellWidth(cell); n > widths[i] {
				widths[i] = n
			}
		}
	}

	writeRow(b, t.head, widths)

	sep := make([]string, len(widths))
	for i, w := range widths {
		sep[i] = strings.Repeat("-", w)
	}
	writeRow(b, sep, widths)

	for _, row := range t.rows {
		writeRow(b, row, widths)
	}
}

// writeRow writes one padded pipe row.
func writeRow(b *strings.Builder, cells []string, widths []int) {
	b.WriteString("|")
	for i, cell := range cells {
		padded := escapeCell(cell)
		b.WriteString(" " + padded + strings.Repeat(" ", widths[i]-cellWidth(cell)) + " |")
	}
	b.WriteString("\n")
}

// escapeCell keeps a pipe inside a value from ending the column.
func escapeCell(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

// cellWidth counts runes, not bytes. The em dash used for an empty cell
// is three bytes wide and one column wide, and padding by bytes puts
// every table row out of alignment from the first dash onward.
func cellWidth(s string) int { return utf8.RuneCountInString(escapeCell(s)) }

// codeList renders a name set as inline code, or an em dash when empty.
func codeList(names []string) string {
	if len(names) == 0 {
		return coverUnknown
	}

	out := make([]string, 0, len(names))
	for _, n := range names {
		out = append(out, "`"+n+"`")
	}

	return strings.Join(out, ", ")
}

// typeCell renders a documented type, which often contains a pipe.
func typeCell(t string) string { return orDash(codeOrEmpty(t)) }

// codeOrEmpty wraps a non-empty value in code ticks.
func codeOrEmpty(s string) string {
	if s == "" {
		return ""
	}

	return "`" + s + "`"
}

// orDash renders an empty value as an em dash so no table cell is blank.
func orDash(s string) string {
	if s == "" {
		return coverUnknown
	}

	return s
}
